# Generated by Django 5.0 on 2024-01-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'biz bilan boglaning'},
        ),
        migrations.AlterModelOptions(
            name='mashgulot',
            options={'verbose_name': 'mashgulotlar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Oqituvchilar'},
        ),
    ]
