# Generated by Django 5.0 on 2024-01-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_us_options_alter_mashgulot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'xizmatlar'},
        ),
    ]
