# Generated by Django 5.0 on 2024-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'biz bilan boglaning'},
        ),
        migrations.AlterModelOptions(
            name='mashgulot',
            options={'verbose_name_plural': 'mashgulotlar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Oqituvchilar'},
        ),
    ]
