# Generated by Django 5.0 on 2024-01-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_us_options_alter_mashgulot_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service1_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='mashgulot',
            name='mashgulot_icon',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
