# Generated by Django 5.0 on 2024-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_service1_name_service_service_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mashgulot',
            old_name='boshlainish_vaqti',
            new_name='boshlanish_vaqti',
        ),
        migrations.RenameField(
            model_name='mashgulot',
            old_name='tugashsh_vaqti',
            new_name='tugash_vaqti',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_icon',
        ),
    ]
